version: '3.8'

services:
  db_mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: orit_schema
      MYSQL_USER: orit
      MYSQL_PASSWORD: oritpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  api:
    build:
      context: .
      dockerfile: apps/orit-teste/Dockerfile
    container_name: api_service
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: db_mysql
      DATABASE_PORT: 3306
      DATABASE_USER: orit
      DATABASE_PASSWORD: oritpassword
      DATABASE_NAME: orit_schema
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db_mysql
      - redis
    networks:
      - app_network
    volumes:
      - ./apps/orit-teste/src:/app/src  # Mapeie o diretório de código fonte
      - /app/node_modules  # Para evitar problemas com o diretório node_modules

  worker:
    build:
      context: .
      dockerfile: apps/orit-teste-job/Dockerfile
    container_name: worker_service
    env_file:
      - .env
    ports:
      - "3001:3001"
    environment:
      DATABASE_HOST: db_mysql
      DATABASE_PORT: 3306
      DATABASE_USER: orit
      DATABASE_PASSWORD: oritpassword
      DATABASE_NAME: orit_schema
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db_mysql
      - redis
    networks:
      - app_network
    volumes:
      - ./apps/orit-teste-job/src:/app/src  # Mapeie o diretório de código fonte
      - /app/node_modules  # Para evitar problemas com o diretório node_modules


volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local

networks:
  app_network:
    driver: bridge
